default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: dell
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vuz_db

test:
  <<: *default
  database: vuz_db_test

production:
  <<: *default
  database: vuz_db_production
